### PR TITLE
LPS-158932 Allow for userID to be passed correctly when using Experiences with Workflow

### PR DESCRIPTION
**Pull request by jakesliwka**
https://issues.liferay.com/browse/LPP-45997

While having workflow enabled and creating a new page with multiple experiences, once approved, the pages would appear as blank.

This was because only when workflow was enabled, and **updateLayoutPageTemplateStructureData** was called, a user ID of 0 was passed passed in to the _layoutPageTemplateStructureRelLocalService.addLayoutPageTemplateStructureRel method which threw an error saying that there cannot be a userId of 0. This caused the experiences to not display their changes made, despite being 'approved'. When tested with workflow disabled, the correct userID gets passed each time.

The userID was being retrieved with **PrincipalThreadLocal.getUserId()** . The solution was to go back to when we had a valid userID and pass it along to make sure that a correct one is used and set it back afterwards, as well as ensure that it is not used anywhere else during the process.

We decided to pass in a valid userId to **_layoutCopyHelper.copyLayout(draftLayout, layout)** located in **LayoutWorkflowHandler.java**, which ensures that these changes are only called when workflow is enabled.

Testing resulted in confirming that with the applied changes, the behavior is very similar to publishing a page without workflow, passing the correct userId's when needed.

The worry was that if workflow and publications were to be eventually integrated, this issue could potentially pass the wrong userId.
This [PTR](https://issues.liferay.com/browse/PTR-3253) confirmed that since workflow does not work with publications, this fix can proceed safely.

### CODE REVIEW

**Comment by jakesliwka** [comment]
ci:test:sf

**Comment by jakesliwka** [comment]
ci:test:stable

**Comment by jakesliwka** [comment]
ci:test:relevant

**Comment by jakesliwka** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
Hi @jakesliwka,
So I don't think the correct userId is being set here. Here are the steps I took to verify:

1. Create two admin users for the liferay site ("test1" and "test2")
2. Create a content page under the original user "test" with a heading
3. Place a breakpoint in `LayoutPageTemplateStructureRelLocalServiceImpl.addLayoutPageTemplateStructureRel  `
4. Edit the page and add an experience
5. Check the breakpoint and see that "test" is the user being passed here.
6. Login as "test1" and edit the page to add an experience.
7. Check the breakpoint and see that the user being used here is "test1"
8. This tells us that the correct user to pass into `addLayoutPageTemplateStructureRel` is the current publisher of the page
9. Now enable workflow
10. Login with "test2" and edit the page to add an experience. Submit for publication
11. Login as "test1" and approve the submission.
12. Check the breakpoint. Based on your fix, the user being set to PrincipalThreadLocal is "test1". This is the user that approved the page, not the actual publisher. I think the correct user that should be passed in this scenario is "test2".

Can you go back to your fix and see if you can find the correct user to set to PrincipalThreadLocal?
Let me know if any clarifications are needed.

As a side note, please make sure to link the LPS ticket in the description of the PR, not the LPP.

Thanks!

**Pull request closed without merging**
